name: build-windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      - name: Flutter doctor
        run: flutter doctor -v
      - name: Flutter pub get
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: strat_column_builder_windows
          path: build/windows/x64/runner/Release/
